/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KlinikPekapuran;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nur
 */
public class Biaya extends javax.swing.JInternalFrame {

    public final Connection Conn = new Koneksi().Connect();
    private DefaultTableModel tablemodel;
    
       public void tableBiaya(){
        Object baris[]={"ID Biaya", "ID Poli Umum", "ID Poli Gigi", "ID Pelayanan Bidan", "Nama Pasien", "Tanggal Berobat", "Nama Dokter", "Biaya Layanan", "Biaya Berobat", "Total Biaya", "Catatan"};
        tablemodel = new DefaultTableModel(null, baris);
        tabelBiaya.setModel(tablemodel);
        String sql = " select * from informasi_biaya order by id_biaya asc";
        try{
            java.sql.Statement put = Conn.createStatement();
            ResultSet hasil = put.executeQuery(sql);
            while (hasil.next()){
                String id_biaya = hasil.getString("id_biaya");
                String id_poliumum = hasil.getString("id_poliumum");
                String id_poligigi = hasil.getString("id_poligigi");
                String id_bidan = hasil.getString("id_bidan");
                String nama_pasien = hasil.getString("nama_pasien");
                String tgl_berobat = hasil.getString("tgl_berobat");
                String nama_dokter = hasil.getString("nama_dokter");
                String biaya_layanan = hasil.getString("biaya_layanan");
                String biaya_obat = hasil.getString("biaya_obat");
                String total = hasil.getString("total");
                String catatan = hasil.getString("catatan");
                
                String hasilAll[] = {id_biaya, id_poliumum, id_poligigi, id_bidan, nama_pasien, tgl_berobat,  nama_dokter, biaya_layanan, biaya_obat, total, catatan};
                tablemodel.addRow(hasilAll);
            }
            
        } catch (Exception e){}
        
    }
    
    public Biaya() {
        initComponents();
        tableBiaya();
        
        
    }
    
    protected void blank(){
        id_poligigi.setText("");
        id_biaya.setText("");
        id_poliumum.setText("");
        id_bidan.setText("");
        nama_dokter.setSelectedIndex(0);
        tgl_berobat.setDate(Date.from(Instant.now()));
        catatan.setText("");
        biaya_layanan.setText("");
        id_pasien.setText("");
        biaya_obat.setText("");
        nama_pasien.setText("");
        jenis_kelamin.setSelectedIndex(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id_bidan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_pasien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nama_dokter = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tgl_berobat = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        Hapus1 = new javax.swing.JButton();
        Simpan1 = new javax.swing.JButton();
        Ubah = new javax.swing.JButton();
        CariPasien = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatan = new javax.swing.JTextArea();
        biaya_layanan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        biaya_obat = new javax.swing.JTextField();
        id_poliumum = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        id_poligigi = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jenis_kelamin = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        total_biaya = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelBiaya = new javax.swing.JTable();
        print = new javax.swing.JButton();
        id_biaya = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1541, 800));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Informasi Biaya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID Poli Umum   :");

        id_bidan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_bidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_bidanActionPerformed(evt);
            }
        });
        id_bidan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_bidanKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("ID Pasien");

        id_pasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        nama_dokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nama_dokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Abu Bakar", "Ibnu Malik", "Ibnu Sina", "Yopie", "Yahya Syafrudin", "Nizam", "Puji Astuti", "Ibnu Batutah", "Siti Badriyah", "Raisa Andriyana" }));
        nama_dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_dokterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Berobat");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Biaya Layanan");

        Hapus1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Hapus1.setText("Hapus");
        Hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hapus1ActionPerformed(evt);
            }
        });

        Simpan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Simpan1.setText("Simpan");
        Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan1ActionPerformed(evt);
            }
        });

        Ubah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ubah.setText("Ubah");
        Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahActionPerformed(evt);
            }
        });

        CariPasien.setBackground(new java.awt.Color(0, 102, 102));
        CariPasien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CariPasien.setText("Cek ID");
        CariPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariPasienActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Catatan");

        catatan.setColumns(20);
        catatan.setRows(5);
        jScrollPane2.setViewportView(catatan);

        biaya_layanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Biaya Obat");

        biaya_obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        id_poliumum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_poliumum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_poliumumActionPerformed(evt);
            }
        });
        id_poliumum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_poliumumKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("ID PoliGigi  :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID Layanan Bidan :");

        id_poligigi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_poligigi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_poligigiKeyPressed(evt);
            }
        });

        nama_pasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nama Pasien");

        jenis_kelamin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jenis_kelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Laki-laki", "Perempuan" }));
        jenis_kelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenis_kelaminActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Dokter");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Total");

        total_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_biayaActionPerformed(evt);
            }
        });
        total_biaya.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total_biayaKeyPressed(evt);
            }
        });

        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("masukan salah satu id untuk cekdata medis");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(id_pasien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CariPasien)
                                        .addGap(186, 186, 186))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(id_poliumum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel12)
                                                .addGap(9, 9, 9)
                                                .addComponent(id_poligigi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(id_bidan, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 27, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(Hapus1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Simpan1)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(nama_dokter, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                    .addComponent(total_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                    .addComponent(biaya_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                    .addComponent(jLabel13)))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(biaya_obat, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                                                        .addComponent(jScrollPane2))
                                                    .addComponent(jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(tgl_berobat, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(id_bidan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_poliumum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(id_poligigi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CariPasien)
                    .addComponent(id_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nama_pasien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_kelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tgl_berobat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(biaya_layanan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(biaya_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_dokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus1)
                    .addComponent(Simpan1))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cetak Struk");

        tabelBiaya.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelBiaya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        tabelBiaya.setRowHeight(25);
        tabelBiaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBiayaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelBiaya);

        print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        print.setText("PRINT by ID");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("* id harus di isi ketika menyimpan data !!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(print)
                    .addComponent(id_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_dokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_dokterActionPerformed

    private void CariPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariPasienActionPerformed
       try {
              String sql="Select * from pasien where id_pasien like '%" + id_pasien.getText() + "%'";          
              java.sql.Statement put = Conn.createStatement();
              ResultSet rs = put.executeQuery(sql);
           
                if(rs.next()){
                                       String add1 = rs.getString("nama_pasien");
                                       nama_pasien.setText(add1);
                                       String add2 =rs.getString("jenis_kelamin");
                                       jenis_kelamin.setSelectedItem(add2);
                               }
                biaya_layanan.requestFocus();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CariPasienActionPerformed

    private void id_bidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_bidanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_bidanActionPerformed

    private void id_poliumumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_poliumumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_poliumumActionPerformed

    private void jenis_kelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenis_kelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenis_kelaminActionPerformed

    private void id_poliumumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_poliumumKeyPressed

          try {
              String sql="Select * from rm_poliumum where id_poliumum like '%" + id_poliumum.getText() + "%'";          
              java.sql.Statement put = Conn.createStatement();
              ResultSet rs = put.executeQuery(sql);
           
                if(rs.next()){
                                       Date t = rs.getDate("tgl_berobat");
                                       tgl_berobat.setDate(t);
                                       String add1 = rs.getString("nama_dokter");
                                       nama_dokter.setSelectedItem(add1);
                                       String add2 =rs.getString("keluhan");
                                       catatan.setText(add2);
                                       String add4 = rs.getString("diagnosa");
                                       catatan.setText(add4);
                                       String add5 = rs.getString("resep_obat");
                                       catatan.setText(add5);
                                       String add6 = rs.getString("id_pasien");
                                       id_pasien.setText(add6);
                               }
                

        } catch (Exception e) {
        }
    }//GEN-LAST:event_id_poliumumKeyPressed

    private void Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan1ActionPerformed
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = String.valueOf(format.format(tgl_berobat.getDate()));

        
        
        String sql = "insert into informasi_biaya values (?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = Conn.prepareStatement(sql);
            stat.setString(1, id_biaya.getText());
            stat.setString(2, id_poliumum.getText());
            stat.setString(3, id_poligigi.getText());
            stat.setString(4, id_bidan.getText());
            stat.setString(5, nama_pasien.getText());
            stat.setString(6, tgl);  
            stat.setString(7, nama_dokter.getSelectedItem().toString());
            stat.setString(8, biaya_layanan.getText());
            stat.setString(9, biaya_obat.getText());            
            stat.setString(10, total_biaya.getText());
            stat.setString(11, catatan.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data akan disimpan");
            blank();
            id_poliumum.requestFocus();
            tableBiaya();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal disimpan"+e);
            tableBiaya();
        }
    }//GEN-LAST:event_Simpan1ActionPerformed

    private void total_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_biayaActionPerformed

    private void total_biayaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_biayaKeyPressed

    }//GEN-LAST:event_total_biayaKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int a = Integer.parseInt(biaya_layanan.getText());
        int b = Integer.parseInt(biaya_obat.getText());
        String hasil = String.valueOf(a+b);
        total_biaya.setText(hasil);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void id_poligigiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_poligigiKeyPressed
         try {
              String sql="Select * from rm_poligigi where id_poligigi like '%" + id_poligigi.getText() + "%'";          
              java.sql.Statement put = Conn.createStatement();
              ResultSet rs = put.executeQuery(sql);
           
                if(rs.next()){
                                       Date t = rs.getDate("tgl_berobat");
                                       tgl_berobat.setDate(t);
                                       String add1 = rs.getString("nama_dokter");
                                       nama_dokter.setSelectedItem(add1);
                                       String add2 =rs.getString("keluhan");
                                       catatan.setText(add2);
                                       String add4 = rs.getString("diagnosa");
                                       catatan.setText(add4);
                                       String add6 = rs.getString("id_pasien");
                                       id_pasien.setText(add6);
                               }
//                                                       catatan.setText(add4);
//                                       String add5 = rs.getString("resep_obat");


        } catch (Exception e) {
        }
    }//GEN-LAST:event_id_poligigiKeyPressed

    private void id_bidanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_bidanKeyPressed
                  try {
              String sql="Select * from rm_bidan where id_bidan like '%" + id_bidan.getText() + "%'";          
              java.sql.Statement put = Conn.createStatement();
              ResultSet rs = put.executeQuery(sql);
           
                if(rs.next()){
                                       Date t = rs.getDate("tgl_berobat");
                                       tgl_berobat.setDate(t);
                                       String add1 = rs.getString("nama_dokter");
                                       nama_dokter.setSelectedItem(add1);
                                       String add2 =rs.getString("keluhan");
                                       catatan.setText(add2);
                                       String add4 = rs.getString("diagnosa");
                                       catatan.setText(add4);
                                       String add5 = rs.getString("resep_obat");
                                       catatan.setText(add5);
                                       String add6 = rs.getString("id_pasien");
                                       id_pasien.setText(add6);
                               }
                

        } catch (Exception e) {
        }
    }//GEN-LAST:event_id_bidanKeyPressed

    private void tabelBiayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBiayaMouseClicked
                // TODO add your handling code here:
      SimpleDateFormat tglview = new SimpleDateFormat("yyyy-MM-dd");   
        
     //if (evt.getClickCount()==1) { 
        Date dateView = null;
        int baris = tabelBiaya.getSelectedRow();
        try {
                dateView = tglview.parse((String) tabelBiaya.getValueAt(baris, 5));
            } catch (ParseException ex) {
                Logger.getLogger(Biaya.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        id_biaya.setText(tabelBiaya.getModel().getValueAt(baris, 0).toString());
        id_poliumum.setText(tabelBiaya.getModel().getValueAt(baris, 1).toString());
        id_poligigi.setText(tabelBiaya.getModel().getValueAt(baris, 2).toString());
        id_bidan.setText(tabelBiaya.getModel().getValueAt(baris, 3).toString());
        nama_pasien.setText(tabelBiaya.getModel().getValueAt(baris, 4).toString()); 
        tgl_berobat.setDate(dateView);
       nama_dokter.setSelectedItem(tabelBiaya.getModel().getValueAt(baris, 6).toString());
       biaya_layanan.setText(tabelBiaya.getModel().getValueAt(baris, 7).toString());
       biaya_obat.setText(tabelBiaya.getModel().getValueAt(baris, 8).toString());
       total_biaya.setText(tabelBiaya.getModel().getValueAt(baris, 9).toString());
       catatan.setText(tabelBiaya.getModel().getValueAt(baris, 10).toString());
    }//GEN-LAST:event_tabelBiayaMouseClicked

    private void UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahActionPerformed

        SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");   
        String tgl = String.valueOf(fm.format(tgl_berobat.getDate()));
        try{
            String sql = "update informasi_biaya set "
                    + "id_biaya=?,"
                     + "id_poliumum=?,"
                     + "id_poligigi=?,"
                     + "id_bidan=?,"
                    + "nama_pasien=?,"
                    + "tgl_berobat=?,"
                    + "nama_dokter=?, "
                    + "biaya_layanan=?, "
                     + "biaya_obat=?,"
                     + "total=?,"
                     + "catatan=? "
                    + "where id_biaya='"+id_biaya.getText()+"'";
            PreparedStatement stat = Conn.prepareStatement(sql);
            stat.setString(1, id_biaya.getText());
            stat.setString(2, id_poliumum.getText());
            stat.setString(3, id_poligigi.getText());
            stat.setString(4, id_bidan.getText());
            stat.setString(5, nama_pasien.getText());
            stat.setString(6, tgl);
            stat.setString(7, nama_dokter.getSelectedItem().toString());
            stat.setString(8, biaya_layanan.getText());
            stat.setString(9, biaya_obat.getText());            
            stat.setString(10, total_biaya.getText());
            stat.setString(11, catatan.getText());
    
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data akan diubah");
            blank();
            id_biaya.requestFocus();
            }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data gagal diubah"+e);
            }
            tableBiaya();
    }//GEN-LAST:event_UbahActionPerformed

    private void Hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hapus1ActionPerformed
                 int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "delete from informasi_biaya where id_pbiaya ='"+id_biaya.getText()+"'";
             try{
                PreparedStatement stat = Conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                blank();
                id_biaya.requestFocus();
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
             }
         
         }
    }//GEN-LAST:event_Hapus1ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
             java.sql.Connection Conn = null;
             try{
                String jdbcDriver = "com.mysql.jdbc.Driver";
                Class.forName(jdbcDriver);
                
                String url = "jdbc:mysql://localhost:3306/dbklinik_pekapuran";
                String user = "root";
                String pas = "";
                
                Conn = DriverManager.getConnection(url, user, pas);
                Statement stat = Conn.createStatement();
                
                try{
                    String report = "A:\\temporary_project\\NetBeansProjects\\Kel2\\src\\KlinikPekapuran\\report\\report1.jrxml";
                    HashMap hs = new HashMap();
                    //menggambil parameter
                    hs.put("id_biaya", id_biaya.getText());
                    JasperReport JRpt = JasperCompileManager.compileReport(report);
                    JasperPrint JRprint = JasperFillManager.fillReport(JRpt, hs, Conn);
                    JasperViewer.viewReport(JRprint, false);
                }catch(Exception e) {
                    JOptionPane.showMessageDialog(null, "Tidak Bisa Review Print" + e);
                }
             }
                catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
             } catch (ClassNotFoundException ex) {
            Logger.getLogger(Biaya.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariPasien;
    private javax.swing.JButton Hapus1;
    private javax.swing.JButton Simpan1;
    private javax.swing.JButton Ubah;
    private javax.swing.JTextField biaya_layanan;
    private javax.swing.JTextField biaya_obat;
    private javax.swing.JTextArea catatan;
    private javax.swing.JTextField id_biaya;
    private javax.swing.JTextField id_bidan;
    private javax.swing.JTextField id_pasien;
    private javax.swing.JTextField id_poligigi;
    private javax.swing.JTextField id_poliumum;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jenis_kelamin;
    private javax.swing.JComboBox<String> nama_dokter;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JButton print;
    private javax.swing.JTable tabelBiaya;
    private com.toedter.calendar.JDateChooser tgl_berobat;
    private javax.swing.JTextField total_biaya;
    // End of variables declaration//GEN-END:variables
}
