/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KlinikPekapuran;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author Nur
 */
public class MenuUtama extends javax.swing.JFrame {
    private final Connection Conn = new Koneksi().Connect();
    private InformasiUmum Informasi;
    Fasilitas Fasilitas;  
    Pendaftaran Pendaftaran;
    
    PoliUmum PoliUmum;
    PoliGigi PoliGigi;
    Bidan Bidan;
    
    Biaya Biaya;
    
    Laporan_poliUmum rPoliUmum;
    Laporan_poligigi rPoliGigi;
    Laporan_bidan rBidan;
    Laporan_DataObat rObat;
    Laporan_karyawan rKaryawan;
    
    
    
    private void initForm(){
        Informasi = new InformasiUmum();
        Fasilitas = new Fasilitas();           
        Pendaftaran = new Pendaftaran();
        
        PoliUmum = new PoliUmum();
        PoliGigi= new PoliGigi();
        Bidan = new Bidan();
        
        Biaya = new Biaya();
        
        rPoliUmum= new Laporan_poliUmum();
        rPoliGigi= new Laporan_poligigi();
        rBidan= new Laporan_bidan();
        rObat = new Laporan_DataObat();
        rKaryawan = new Laporan_karyawan();
    }

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        initForm();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        DataInduk = new javax.swing.JMenu();
        InformasiUmum = new javax.swing.JMenuItem();
        menuFasilitas = new javax.swing.JMenuItem();
        menuPendaftaran = new javax.swing.JMenuItem();
        Pelayanan = new javax.swing.JMenu();
        menuPoliUmum = new javax.swing.JMenuItem();
        menuPoliGigi = new javax.swing.JMenuItem();
        menuBidan = new javax.swing.JMenuItem();
        MenuBiaya = new javax.swing.JMenu();
        Laporan2 = new javax.swing.JMenu();
        DataPoliUmum = new javax.swing.JMenuItem();
        DataPoliGigi = new javax.swing.JMenuItem();
        DataPelyananBidan = new javax.swing.JMenuItem();
        DataObat = new javax.swing.JMenuItem();
        karyawan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setBackground(new java.awt.Color(0, 153, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setIconImages(null);

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 204));

        jDesktopPane1.setBackground(new java.awt.Color(153, 153, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDesktopPane1.setForeground(new java.awt.Color(0, 204, 0));
        jDesktopPane1.setToolTipText("KLINIK PEKAPURAN");
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistem Pelayanan Antrian ");

        jLabel2.setFont(new java.awt.Font("BankGothic Md BT", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelompok 2");

        jLabel3.setFont(new java.awt.Font("BankGothic Md BT", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Klinik Pekapuran");

        jLabel4.setFont(new java.awt.Font("BankGothic Md BT", 3, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KlinikGede.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(646, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 102));

        DataInduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        DataInduk.setText("Beranda");
        DataInduk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataInduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DataInduk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DataInduk.setIconTextGap(10);
        DataInduk.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DataInduk.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        InformasiUmum.setBackground(new java.awt.Color(0, 102, 102));
        InformasiUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        InformasiUmum.setText("Informasi Umum");
        InformasiUmum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformasiUmum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        InformasiUmum.setIconTextGap(1);
        InformasiUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformasiUmumActionPerformed(evt);
            }
        });
        DataInduk.add(InformasiUmum);

        menuFasilitas.setBackground(new java.awt.Color(0, 102, 102));
        menuFasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuFasilitas.setText("Fasilitas");
        menuFasilitas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFasilitasActionPerformed(evt);
            }
        });
        DataInduk.add(menuFasilitas);

        menuPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuPendaftaran.setText("Pendaftaran");
        menuPendaftaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPendaftaranActionPerformed(evt);
            }
        });
        DataInduk.add(menuPendaftaran);

        jMenuBar1.add(DataInduk);

        Pelayanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/layanan2.png"))); // NOI18N
        Pelayanan.setText("Pelayanan");
        Pelayanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pelayanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Pelayanan.setIconTextGap(8);
        Pelayanan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        menuPoliUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuPoliUmum.setText("Poli Umum");
        menuPoliUmum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPoliUmum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuPoliUmum.setIconTextGap(1);
        menuPoliUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPoliUmumActionPerformed(evt);
            }
        });
        Pelayanan.add(menuPoliUmum);

        menuPoliGigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuPoliGigi.setText("Poli Gigi");
        menuPoliGigi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPoliGigi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuPoliGigi.setIconTextGap(1);
        menuPoliGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPoliGigiActionPerformed(evt);
            }
        });
        Pelayanan.add(menuPoliGigi);

        menuBidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        menuBidan.setText("Pelayanan Bidan");
        menuBidan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBidan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuBidan.setIconTextGap(1);
        menuBidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBidanActionPerformed(evt);
            }
        });
        Pelayanan.add(menuBidan);

        jMenuBar1.add(Pelayanan);

        MenuBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/biaya.png"))); // NOI18N
        MenuBiaya.setText("Informasi Biaya");
        MenuBiaya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBiaya.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MenuBiaya.setIconTextGap(8);
        MenuBiaya.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuBiaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBiayaMouseClicked(evt);
            }
        });
        MenuBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBiayaActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuBiaya);

        Laporan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/laporan.png"))); // NOI18N
        Laporan2.setText("Laporan");
        Laporan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Laporan2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Laporan2.setIconTextGap(8);
        Laporan2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        DataPoliUmum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        DataPoliUmum.setText("Data Pasien PoliUmum");
        DataPoliUmum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPoliUmum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DataPoliUmum.setIconTextGap(1);
        DataPoliUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPoliUmumActionPerformed(evt);
            }
        });
        Laporan2.add(DataPoliUmum);

        DataPoliGigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        DataPoliGigi.setText("Data Pasien PoliGigi");
        DataPoliGigi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPoliGigi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DataPoliGigi.setIconTextGap(1);
        DataPoliGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPoliGigiActionPerformed(evt);
            }
        });
        Laporan2.add(DataPoliGigi);

        DataPelyananBidan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        DataPelyananBidan.setText("Data Pasien Layanan Bidan");
        DataPelyananBidan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataPelyananBidan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DataPelyananBidan.setIconTextGap(1);
        DataPelyananBidan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataPelyananBidanActionPerformed(evt);
            }
        });
        Laporan2.add(DataPelyananBidan);

        DataObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        DataObat.setText("Data Obat");
        DataObat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DataObat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        DataObat.setIconTextGap(1);
        DataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataObatActionPerformed(evt);
            }
        });
        Laporan2.add(DataObat);

        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu.png"))); // NOI18N
        karyawan.setText("Data Karyawan");
        karyawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        karyawan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        karyawan.setIconTextGap(1);
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });
        Laporan2.add(karyawan);

        jMenuBar1.add(Laporan2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFasilitasActionPerformed
    if(!Fasilitas.isVisible()){
        jDesktopPane1.add(Fasilitas);
        Fasilitas.show();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        Informasi.dispose();
        Pendaftaran.dispose();
        PoliUmum.dispose();
        PoliGigi.dispose();
        Bidan.dispose();
        Biaya.dispose();
        rPoliUmum.dispose();
        rObat.dispose();
        rPoliGigi.dispose();
        rBidan.dispose();
        rKaryawan.dispose();
        }
    }//GEN-LAST:event_menuFasilitasActionPerformed

    private void MenuBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBiayaActionPerformed
   
    }//GEN-LAST:event_MenuBiayaActionPerformed

    private void InformasiUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformasiUmumActionPerformed
    if(!Informasi.isVisible()){
        jDesktopPane1.add(Informasi);
        Informasi.show();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        Fasilitas.dispose();
        Pendaftaran.dispose();
        PoliUmum.dispose();
        PoliGigi.dispose();
        Bidan.dispose();
        Biaya.dispose();
        rPoliUmum.dispose();
        rObat.dispose();
        rPoliGigi.dispose();
        rBidan.dispose();
        rKaryawan.dispose();
        }
    }//GEN-LAST:event_InformasiUmumActionPerformed

    private void menuPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPendaftaranActionPerformed
        if(!Pendaftaran.isVisible()){
            jDesktopPane1.add(Pendaftaran);
            Pendaftaran.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);

            Informasi.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            Fasilitas.dispose();
            rPoliUmum.dispose();
            rObat.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_menuPendaftaranActionPerformed

    private void menuPoliUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPoliUmumActionPerformed
    if(!PoliUmum.isVisible()){
            jDesktopPane1.add(PoliUmum);
            PoliUmum.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);

            
            Informasi.dispose();
            Pendaftaran.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            Biaya.dispose();    
            Fasilitas.dispose();
            rPoliUmum.dispose();
            rObat.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();   
            rKaryawan.dispose();

        }
    }//GEN-LAST:event_menuPoliUmumActionPerformed

    private void menuPoliGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPoliGigiActionPerformed
        if(!PoliGigi.isVisible()){
            jDesktopPane1.add(PoliGigi);
            PoliGigi.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            Bidan.dispose();
            rPoliUmum.dispose();
            rObat.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_menuPoliGigiActionPerformed

    private void menuBidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBidanActionPerformed
          if(!Bidan.isVisible()){
            jDesktopPane1.add(Bidan);
            Bidan.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            rPoliUmum.dispose();
            rObat.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_menuBidanActionPerformed

    private void DataPoliUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPoliUmumActionPerformed
        if(!rPoliUmum.isVisible()){
            jDesktopPane1.add(rPoliUmum);
            
            rPoliUmum.show();   
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            
            rObat.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_DataPoliUmumActionPerformed

    private void DataPoliGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPoliGigiActionPerformed
        if(!rPoliGigi.isVisible()){
            jDesktopPane1.add(rPoliGigi);
            rPoliGigi.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            rPoliUmum.dispose();
            
            rObat.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_DataPoliGigiActionPerformed

    private void MenuBiayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBiayaMouseClicked
        if(!Biaya.isVisible()){
        jDesktopPane1.add(Biaya);
        Biaya.show();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        Informasi.dispose();
        Pendaftaran.dispose();
        PoliUmum.dispose();
        PoliGigi.dispose();
        Bidan.dispose();
        Fasilitas.dispose();
        rPoliUmum.dispose();
        rObat.dispose();
        rPoliGigi.dispose();
        rBidan.dispose();
        rKaryawan.dispose();
        }
    }//GEN-LAST:event_MenuBiayaMouseClicked

    private void DataPelyananBidanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataPelyananBidanActionPerformed
         if(!rBidan.isVisible()){
            jDesktopPane1.add(rBidan);
            rBidan.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            rPoliUmum.dispose();
            
            rPoliGigi.dispose();
            rObat.dispose();
            Biaya.dispose();
            rKaryawan.dispose();
        }
    }//GEN-LAST:event_DataPelyananBidanActionPerformed

    private void DataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataObatActionPerformed
         if(!rObat.isVisible()){
            jDesktopPane1.add(rObat);
            rObat.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            rPoliUmum.dispose();
            
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
        }
    }//GEN-LAST:event_DataObatActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
         if(!rKaryawan.isVisible()){
            jDesktopPane1.add(rKaryawan);
            rKaryawan.show();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
            
            Informasi.dispose();
            Pendaftaran.dispose();
            Fasilitas.dispose();
            PoliUmum.dispose();
            PoliGigi.dispose();
            Bidan.dispose();
            
            rPoliUmum.dispose();
            rPoliGigi.dispose();
            rBidan.dispose();          
            Biaya.dispose();
            rObat.dispose();
        }
    }//GEN-LAST:event_karyawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DataInduk;
    private javax.swing.JMenuItem DataObat;
    private javax.swing.JMenuItem DataPelyananBidan;
    private javax.swing.JMenuItem DataPoliGigi;
    private javax.swing.JMenuItem DataPoliUmum;
    private javax.swing.JMenuItem InformasiUmum;
    private javax.swing.JMenu Laporan2;
    private javax.swing.JMenu MenuBiaya;
    private javax.swing.JMenu Pelayanan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem karyawan;
    private javax.swing.JMenuItem menuBidan;
    private javax.swing.JMenuItem menuFasilitas;
    private javax.swing.JMenuItem menuPendaftaran;
    private javax.swing.JMenuItem menuPoliGigi;
    private javax.swing.JMenuItem menuPoliUmum;
    // End of variables declaration//GEN-END:variables
}
